/**
 * Dynamic sitemap.xml — generated by Next.js at build/revalidate time.
 *
 * Contains:
 * - Static landing pages (home, explore, community, series listing,
 *   each region hub)
 * - Dynamic per-trail pages (one entry per approved trail)
 * - Dynamic per-series pages (one entry per series slug)
 *
 * Revalidates every hour so freshly added trails/series appear in
 * search results without waiting for the next deploy.
 */
import type { MetadataRoute } from "next";

const API_BASE =
  process.env.NEXT_PUBLIC_API_URL || "https://api.moruwalk.com/api/v1";
const SITE = "https://moruwalk.com";

// Re-render at most once per hour
export const revalidate = 3600;

const REGION_SLUGS = [
  "seoul",
  "gyeonggi",
  "incheon",
  "gangwon",
  "chungcheong",
  "gyeongsang",
  "jeolla",
  "jeju",
];

async function fetchTrailIds(): Promise<{ id: number; updated_at?: string }[]> {
  // Walk the cursor-paginated trails endpoint up to N pages.
  // Each page returns ~50 trails; cap at 20 pages = 1000 trails.
  const out: { id: number; updated_at?: string }[] = [];
  let nextUrl: string | null = `${API_BASE}/trails/?page_size=100`;
  let pages = 0;
  while (nextUrl && pages < 20) {
    try {
      const res: Response = await fetch(nextUrl, { next: { revalidate: 3600 } });
      if (!res.ok) break;
      const data: any = await res.json();
      const results: any[] = Array.isArray(data) ? data : data?.results ?? [];
      for (const t of results) {
        if (typeof t?.id === "number") {
          out.push({ id: t.id, updated_at: t.updated_at });
        }
      }
      nextUrl = (data && typeof data.next === "string") ? data.next : null;
      pages += 1;
    } catch {
      break;
    }
  }
  return out;
}

async function fetchSeriesSlugs(): Promise<string[]> {
  try {
    const res = await fetch(`${API_BASE}/trails/series/`, {
      next: { revalidate: 3600 },
    });
    if (!res.ok) return [];
    const data = await res.json();
    const list: any[] = Array.isArray(data) ? data : data?.results ?? [];
    return list
      .map((s) => (typeof s?.slug === "string" ? s.slug : null))
      .filter((s): s is string => Boolean(s));
  } catch {
    return [];
  }
}

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const now = new Date();

  const staticEntries: MetadataRoute.Sitemap = [
    { url: SITE, lastModified: now, changeFrequency: "daily", priority: 1 },
    { url: `${SITE}/explore`, lastModified: now, changeFrequency: "hourly", priority: 0.9 },
    { url: `${SITE}/series`, lastModified: now, changeFrequency: "daily", priority: 0.9 },
    { url: `${SITE}/community`, lastModified: now, changeFrequency: "hourly", priority: 0.7 },
    { url: `${SITE}/rankings`, lastModified: now, changeFrequency: "hourly", priority: 0.6 },
    ...REGION_SLUGS.map((slug) => ({
      url: `${SITE}/explore/region/${slug}`,
      lastModified: now,
      changeFrequency: "daily" as const,
      priority: 0.8,
    })),
  ];

  const [trails, seriesSlugs] = await Promise.all([
    fetchTrailIds(),
    fetchSeriesSlugs(),
  ]);

  const trailEntries: MetadataRoute.Sitemap = trails.map((t) => ({
    url: `${SITE}/trails/${t.id}`,
    lastModified: t.updated_at ? new Date(t.updated_at) : now,
    changeFrequency: "weekly",
    priority: 0.7,
  }));

  const seriesEntries: MetadataRoute.Sitemap = seriesSlugs.map((slug) => ({
    url: `${SITE}/series/${slug}`,
    lastModified: now,
    changeFrequency: "weekly",
    priority: 0.85,
  }));

  return [...staticEntries, ...trailEntries, ...seriesEntries];
}
