# Generated by Django 4.2.17 on 2026-04-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_siteconfig_business_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('terms', '이용약관'), ('privacy', '개인정보처리방침'), ('location-terms', '위치기반서비스 이용약관'), ('location-privacy', '위치정보 처리방침'), ('marketing-consent', '마케팅 수신 동의')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=100)),
                ('body_markdown', models.TextField(help_text='Markdown (GFM) 지원 — 표, 목록, 굵기 등')),
                ('version', models.CharField(default='1.0', help_text='예: "1.0", "1.1"', max_length=20)),
                ('effective_from', models.DateField(help_text='이 버전이 효력을 발생하는 시작일')),
                ('is_published', models.BooleanField(default=False, help_text='체크 시 공개 API에서 이 슬러그의 최신 노출본이 됩니다')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '약관·방침 문서',
                'verbose_name_plural': '약관·방침 문서',
                'ordering': ['slug', '-effective_from', '-created_at'],
                'indexes': [models.Index(fields=['slug', '-effective_from'], name='community_l_slug_7d0a9b_idx')],
            },
        ),
    ]
