# Generated by Django 4.2.17 on 2026-04-23 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_legaldocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-start_date'], 'verbose_name': '챌린지', 'verbose_name_plural': '챌린지'},
        ),
        migrations.AlterModelOptions(
            name='challengeparticipant',
            options={'ordering': ['-current_value'], 'verbose_name': '챌린지 참가자', 'verbose_name_plural': '챌린지 참가자'},
        ),
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': '댓글 좋아요', 'verbose_name_plural': '댓글 좋아요'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-member_count', '-created_at'], 'verbose_name': '모임', 'verbose_name_plural': '모임'},
        ),
        migrations.AlterModelOptions(
            name='groupmember',
            options={'ordering': ['joined_at'], 'verbose_name': '모임 멤버', 'verbose_name_plural': '모임 멤버'},
        ),
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['created_at'], 'verbose_name': '모임 메시지', 'verbose_name_plural': '모임 메시지'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': '공지사항', 'verbose_name_plural': '공지사항'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': '게시글', 'verbose_name_plural': '게시글'},
        ),
        migrations.AlterModelOptions(
            name='postbookmark',
            options={'verbose_name': '게시글 북마크', 'verbose_name_plural': '게시글 북마크'},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['created_at'], 'verbose_name': '댓글', 'verbose_name_plural': '댓글'},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['order'], 'verbose_name': '게시글 이미지', 'verbose_name_plural': '게시글 이미지'},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name': '게시글 좋아요', 'verbose_name_plural': '게시글 좋아요'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': '신고', 'verbose_name_plural': '신고'},
        ),
        migrations.AlterModelOptions(
            name='userblock',
            options={'verbose_name': '유저 차단', 'verbose_name_plural': '유저 차단'},
        ),
    ]
