# Generated by Django 4.2.29 on 2026-04-04 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=30)),
                ('name_ja', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(blank=True, max_length=100)),
                ('title_ja', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('description_en', models.TextField(blank=True, max_length=1000)),
                ('description_ja', models.TextField(blank=True, max_length=1000)),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(default='KR', max_length=2)),
                ('distance_km', models.DecimalField(decimal_places=1, max_digits=5)),
                ('estimated_minutes', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('easy', '쉬움'), ('moderate', '보통'), ('hard', '어려움')], max_length=10)),
                ('elevation_gain', models.PositiveIntegerField(blank=True, null=True)),
                ('start_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('path_data', models.JSONField(blank=True, default=dict)),
                ('cover_image', models.ImageField(blank=True, upload_to='trails/covers/')),
                ('best_season', models.CharField(choices=[('spring', '봄'), ('summer', '여름'), ('fall', '가을'), ('winter', '겨울'), ('all', '사계절')], default='all', max_length=10)),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('pending', '승인대기'), ('approved', '승인됨'), ('rejected', '반려됨')], default='draft', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trails', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='trails', to='trails.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrailLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='trails.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'trail')},
            },
        ),
        migrations.AddIndex(
            model_name='trail',
            index=models.Index(fields=['region'], name='trails_trai_region_a29ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='trail',
            index=models.Index(fields=['country'], name='trails_trai_country_7efc26_idx'),
        ),
        migrations.AddIndex(
            model_name='trail',
            index=models.Index(fields=['difficulty'], name='trails_trai_difficu_ccc0ef_idx'),
        ),
        migrations.AddIndex(
            model_name='trail',
            index=models.Index(fields=['status'], name='trails_trai_status_d2c1c0_idx'),
        ),
        migrations.AddIndex(
            model_name='trail',
            index=models.Index(fields=['start_lat', 'start_lng'], name='trails_trai_start_l_014444_idx'),
        ),
    ]
