# Generated by Django 4.2.29 on 2026-04-04 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(blank=True, max_length=100)),
                ('title_ja', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('description_en', models.TextField(blank=True, max_length=500)),
                ('description_ja', models.TextField(blank=True, max_length=500)),
                ('cover_image', models.ImageField(blank=True, upload_to='collections/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='trail',
            name='is_multi_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trail',
            name='total_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='trail_type',
            field=models.CharField(choices=[('urban', '도심산책'), ('coastal', '해안길'), ('village', '마을길'), ('cultural', '문화탐방'), ('nature', '자연길'), ('mixed', '복합')], default='mixed', max_length=10),
        ),
        migrations.AddField(
            model_name='trail',
            name='transport_access',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trail',
            name='walking_surface',
            field=models.CharField(choices=[('paved', '포장도로'), ('mixed', '포장+비포장'), ('unpaved', '비포장')], default='paved', max_length=10),
        ),
        migrations.AlterField(
            model_name='trail',
            name='best_season',
            field=models.CharField(choices=[('spring', '봄'), ('summer', '여름'), ('fall', '가을'), ('winter', '겨울'), ('all', '사계절'), ('rainy_ok', '우천 가능')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='trail',
            name='difficulty',
            field=models.CharField(choices=[('easy', '여유롭게'), ('moderate', '보통'), ('hard', '도전적')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='trail',
            index=models.Index(fields=['trail_type'], name='trails_trai_trail_t_1afc2e_idx'),
        ),
        migrations.AddField(
            model_name='collection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='trails',
            field=models.ManyToManyField(blank=True, related_name='collections', to='trails.trail'),
        ),
    ]
