# Generated by Django 4.2.29 on 2026-04-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_collection_trail_is_multi_day_trail_total_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='External thumbnail image URL', max_length=500),
        ),
    ]
