# Generated by Django 4.2.29 on 2026-04-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0005_alter_trail_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-created_at'], 'verbose_name': '컬렉션', 'verbose_name_plural': '컬렉션'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '태그', 'verbose_name_plural': '태그'},
        ),
        migrations.AlterModelOptions(
            name='trail',
            options={'ordering': ['-created_at'], 'verbose_name': '코스', 'verbose_name_plural': '코스'},
        ),
        migrations.AlterModelOptions(
            name='traillike',
            options={'verbose_name': '코스 좋아요', 'verbose_name_plural': '코스 좋아요'},
        ),
    ]
