# Generated by Django 4.2.29 on 2026-04-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0012_safer_author_and_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trail',
            new_name='trails_trai_is_offi_c95cd5_idx',
            old_name='trails_trai_is_offi_b75abe_idx',
        ),
        migrations.RenameIndex(
            model_name='trail',
            new_name='trails_trai_status_226a32_idx',
            old_name='trails_trai_status_b8f3c1_idx',
        ),
        migrations.RenameIndex(
            model_name='trailbookmark',
            new_name='trails_trai_user_id_eca946_idx',
            old_name='trails_trai_user_id_2dd04c_idx',
        ),
        migrations.RenameIndex(
            model_name='trailcompletion',
            new_name='trails_trai_user_id_0546cf_idx',
            old_name='trails_trai_user_id_a9edc6_idx',
        ),
        migrations.RenameIndex(
            model_name='trailcompletion',
            new_name='trails_trai_trail_i_f7ebb2_idx',
            old_name='trails_trai_trail_i_dc9f3b_idx',
        ),
        migrations.RenameIndex(
            model_name='trailcondition',
            new_name='trails_trai_trail_i_6e7a70_idx',
            old_name='trails_trai_trail_i_e0b7bc_idx',
        ),
        migrations.RenameIndex(
            model_name='trailcondition',
            new_name='trails_trai_tag_a085ff_idx',
            old_name='trails_trai_tag_5c9e88_idx',
        ),
        migrations.RenameIndex(
            model_name='trailseriestrail',
            new_name='trails_trai_series__01524b_idx',
            old_name='trails_trai_series__d1aff0_idx',
        ),
        migrations.AlterField(
            model_name='trailcompletion',
            name='coverage',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='0.000 ~ 1.000 — fraction of trail path walked', max_digits=4),
        ),
    ]
