# Generated by Django 4.2.17 on 2026-04-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0015_stamppoint_userstamp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stamppoint',
            new_name='trails_stam_trail_i_5e6214_idx',
            old_name='trails_stam_trail_i_8d2f3a_idx',
        ),
        migrations.RenameIndex(
            model_name='userstamp',
            new_name='trails_user_user_id_d30786_idx',
            old_name='trails_user_user_id_4b7c1e_idx',
        ),
    ]
