# Generated by Django 4.2.17 on 2026-04-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0016_rename_trails_stam_trail_i_8d2f3a_idx_trails_stam_trail_i_5e6214_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='visibility',
            field=models.CharField(choices=[('private', '나만 보기'), ('public', '공유 (공개)')], db_index=True, default='private', help_text='private: 본인만 조회 / public: 공개 피드 노출', max_length=10),
        ),
    ]
