# Generated by Django 4.2.29 on 2026-04-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_notification_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationlog',
            options={'ordering': ['-created_at'], 'verbose_name': '운영 로그', 'verbose_name_plural': '운영 로그'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': '알림', 'verbose_name_plural': '알림'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': '신고', 'verbose_name_plural': '신고'},
        ),
    ]
