# Generated by Django 4.2.17 on 2026-04-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_add_ai_moderation_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aimoderationlog',
            new_name='moderation__content_738c60_idx',
            old_name='moderation_a_content_idx',
        ),
        migrations.RenameIndex(
            model_name='aimoderationlog',
            new_name='moderation__action_a4593c_idx',
            old_name='moderation_a_action_idx',
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='action',
            field=models.CharField(choices=[('approve', '승인'), ('reject', '반려'), ('delete', '삭제'), ('flag', '플래그'), ('suspend', '유저 정지'), ('lift', '정지 해제'), ('user_delete', '유저 탈퇴 처리'), ('memo', '유저 메모')], max_length=20),
        ),
    ]
