# Generated by Django 4.2.29 on 2026-04-04 04:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trails', '0002_collection_trail_is_multi_day_trail_total_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField()),
                ('planned_time', models.TimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, max_length=200)),
                ('pace', models.CharField(choices=[('slow', '느긋하게'), ('moderate', '보통'), ('fast', '빠르게')], default='moderate', max_length=10)),
                ('companion_status', models.CharField(choices=[('open', '동행 구하는 중'), ('matched', '동행 확정'), ('closed', '모집 마감'), ('completed', '완료')], default='open', max_length=10)),
                ('max_companions', models.PositiveSmallIntegerField(default=3)),
                ('preferred_gender', models.CharField(choices=[('any', '상관없음'), ('male', '남성'), ('female', '여성')], default='any', max_length=10)),
                ('preferred_age_range', models.CharField(choices=[('any', '상관없음'), ('20s', '20대'), ('30s', '30대'), ('40s', '40대'), ('50s_plus', '50대 이상')], default='any', max_length=10)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_plans', to='trails.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['planned_date', 'planned_time'],
            },
        ),
        migrations.CreateModel(
            name='SafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('no_show', '노쇼'), ('inappropriate', '부적절한 행동'), ('harassment', '괴롭힘'), ('scam', '사기'), ('safety_concern', '안전 우려'), ('other', '기타')], max_length=20)),
                ('detail', models.TextField(max_length=500)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('walk_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_reports', to='companions.walkplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tags', models.JSONField(blank=True, default=list)),
                ('content', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_companion_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_companion_reviews', to=settings.AUTH_USER_MODEL)),
                ('walk_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_reviews', to='companions.walkplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('accepted', '수락'), ('rejected', '거절'), ('cancelled', '취소')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_requests', to=settings.AUTH_USER_MODEL)),
                ('walk_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='companions.walkplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
                ('walk_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='companions.walkplan')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='companions.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='walkplan',
            index=models.Index(fields=['planned_date'], name='companions__planned_fce158_idx'),
        ),
        migrations.AddIndex(
            model_name='walkplan',
            index=models.Index(fields=['companion_status'], name='companions__compani_28a54a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companionreview',
            unique_together={('reviewer', 'walk_plan')},
        ),
        migrations.AlterUniqueTogether(
            name='companionrequest',
            unique_together={('requester', 'walk_plan')},
        ),
    ]
