# Generated by Django 4.2.29 on 2026-04-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companions', '0002_chatroom_name_alter_chatroom_walk_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': '채팅 메시지', 'verbose_name_plural': '채팅 메시지'},
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': '채팅방', 'verbose_name_plural': '채팅방'},
        ),
        migrations.AlterModelOptions(
            name='companionrequest',
            options={'ordering': ['-created_at'], 'verbose_name': '동행 요청', 'verbose_name_plural': '동행 요청'},
        ),
        migrations.AlterModelOptions(
            name='companionreview',
            options={'ordering': ['-created_at'], 'verbose_name': '동행 후기', 'verbose_name_plural': '동행 후기'},
        ),
        migrations.AlterModelOptions(
            name='safetyreport',
            options={'ordering': ['-created_at'], 'verbose_name': '안전 신고', 'verbose_name_plural': '안전 신고'},
        ),
        migrations.AlterModelOptions(
            name='walkplan',
            options={'ordering': ['planned_date', 'planned_time'], 'verbose_name': '걷기 일정', 'verbose_name_plural': '걷기 일정'},
        ),
    ]
