# Generated by Django 4.2.29 on 2026-04-04 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age_range',
            field=models.CharField(blank=True, choices=[('20s', '20대'), ('30s', '30대'), ('40s', '40대'), ('50s_plus', '50대 이상')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='companion_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='companion_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='one_liner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_walks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_level',
            field=models.IntegerField(choices=[(0, '미인증'), (1, '이메일 인증'), (2, '본인 인증'), (3, '신뢰 동행자')], default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='walking_style',
            field=models.CharField(blank=True, choices=[('explorer', '탐험가'), ('foodie', '맛집러'), ('photographer', '사진러'), ('talker', '수다쟁이'), ('silent', '조용한 산책')], max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('verified', '본인 인증 ✓'), ('trusted', '신뢰 동행자 🛡️'), ('first_walk', '첫 동행 🌱'), ('companion_10', '길벗 🤝'), ('popular', '인기 동행자 🌟'), ('trail_creator', '코스 개척자 🗺️'), ('storyteller', '스토리텔러 📝')], max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge_type')},
            },
        ),
    ]
