# Generated by Django 4.2.29 on 2026-04-04 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_age_range_customuser_companion_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='badge_type',
            field=models.CharField(choices=[('verified', '본인 인증 ✓'), ('trusted', '신뢰 동행자 🛡️'), ('first_walk', '첫 동행 🌱'), ('companion_10', '길벗 🤝'), ('popular', '인기 동행자 🌟'), ('trail_creator', '코스 개척자 🗺️'), ('storyteller', '스토리텔러 📝'), ('walker_10km', '10km 워커 🚶'), ('walker_50km', '50km 워커 🏃'), ('walker_100km', '100km 워커 🏅'), ('global_walker', '글로벌 워커 🌍')], max_length=20),
        ),
    ]
