# Generated by Django 4.2.29 on 2026-04-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_physical_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '회원', 'verbose_name_plural': '회원'},
        ),
        migrations.AlterModelOptions(
            name='phoneverification',
            options={'ordering': ['-created_at'], 'verbose_name': '휴대폰 인증', 'verbose_name_plural': '휴대폰 인증'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'verbose_name': '배지', 'verbose_name_plural': '배지'},
        ),
    ]
