# Generated by Django 4.2.29 on 2026-04-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneVerification',
        ),
    ]
