# Generated by Django 4.2.17 on 2026-04-22 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_notification_push_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='marketing_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AgreementAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('terms', '이용약관'), ('privacy', '개인정보처리방침'), ('location-terms', '위치기반서비스 이용약관'), ('location-privacy', '위치정보 처리방침'), ('marketing-consent', '마케팅 수신 동의'), ('age-14', '만 14세 이상 확인')], db_index=True, max_length=40)),
                ('version', models.CharField(blank=True, default='', max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '약관 동의 기록',
                'verbose_name_plural': '약관 동의 기록',
                'ordering': ['-accepted_at'],
                'unique_together': {('user', 'slug')},
            },
        ),
    ]
