# Generated by Django 4.2.17 on 2026-04-23 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_marketing_consent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '유저', 'verbose_name_plural': '유저'},
        ),
    ]
