# Generated by Django 4.2.17 on 2026-04-23 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '유저 메모',
                'verbose_name_plural': '유저 메모',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='탈퇴 일시'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deletion_reason',
            field=models.TextField(blank=True, default='', verbose_name='탈퇴 사유'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='탈퇴 여부'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='마지막 로그인 IP'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_user_agent',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='마지막 로그인 디바이스'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(max_length=50, unique=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='전화번호 인증'),
        ),
        migrations.CreateModel(
            name='UserSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='사유')),
                ('suspended_at', models.DateTimeField(auto_now_add=True, verbose_name='정지 시작')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='자동 해제 예정')),
                ('lifted_at', models.DateTimeField(blank=True, null=True, verbose_name='해제 일시')),
                ('lifted_reason', models.TextField(blank=True, default='', verbose_name='해제 사유')),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='해제 처리자')),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='정지 처리자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to=settings.AUTH_USER_MODEL, verbose_name='대상 유저')),
            ],
            options={
                'verbose_name': '정지 기록',
                'verbose_name_plural': '정지 기록',
                'ordering': ['-suspended_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.CharField(blank=True, default='', max_length=300, verbose_name='디바이스 (User-Agent)')),
                ('login_method', models.CharField(blank=True, default='', help_text='예: password, phone, social_google 등', max_length=20, verbose_name='로그인 방식')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='로그인 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '로그인 기록',
                'verbose_name_plural': '로그인 기록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminMemoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='admin_memos/', verbose_name='이미지')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.adminmemo', verbose_name='메모')),
            ],
            options={
                'verbose_name': '유저 메모 첨부',
                'verbose_name_plural': '유저 메모 첨부',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='adminmemo',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='adminmemo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_memos', to=settings.AUTH_USER_MODEL, verbose_name='대상 유저'),
        ),
    ]
