# Generated by Django 4.2.17 on 2026-04-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_adminmemo_customuser_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='전화번호 인증 일시'),
        ),
    ]
