# Generated by Django 4.2.17 on 2026-04-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_phone_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersuspension',
            name='duration',
            field=models.CharField(choices=[('1d', '1일'), ('3d', '3일'), ('5d', '5일'), ('7d', '7일'), ('permanent', '영구정지')], default='7d', max_length=10, verbose_name='정지 기간'),
        ),
    ]
