# Generated by Django 4.2.17 on 2026-04-23 04:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_usersuspension_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersuspension',
            name='scopes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('account', '계정 이용'), ('community', '커뮤니티'), ('trail', '코스 등록'), ('companion', '동행'), ('review', '리뷰/평점')], max_length=20), blank=True, default=list, size=10, verbose_name='정지 범위'),
        ),
        migrations.AlterField(
            model_name='usersuspension',
            name='reason',
            field=models.CharField(max_length=100, verbose_name='사유'),
        ),
    ]
