# Generated by Django 4.2.29 on 2026-04-04 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trails', '0002_collection_trail_is_multi_day_trail_total_days_and_more'),
        ('stories', '0002_walkstory_comment_count_walkstory_trail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual_gpx', 'GPX 파일 업로드'), ('apple_watch', 'Apple Watch'), ('garmin', 'Garmin'), ('samsung_health', 'Samsung Health'), ('google_fit', 'Google Fit'), ('cashwalk', '캐시워크'), ('phone_gps', '스마트폰 GPS'), ('strava', 'Strava')], default='phone_gps', max_length=20)),
                ('gpx_file', models.FileField(blank=True, null=True, upload_to='activities/gpx/')),
                ('track_points', models.JSONField(default=list, help_text='Array of {lat, lng, ele, time}')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_steps', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('elevation_gain_m', models.PositiveIntegerField(blank=True, null=True)),
                ('elevation_loss_m', models.PositiveIntegerField(blank=True, null=True)),
                ('max_elevation_m', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('min_elevation_m', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('avg_speed_kmh', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('max_speed_kmh', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('avg_pace_min_km', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('min_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('max_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('min_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('max_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_tracks', to='stories.walkstory')),
                ('trail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_tracks', to='trails.trail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyActivitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_steps', models.PositiveIntegerField(default=0)),
                ('total_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_duration_minutes', models.PositiveIntegerField(default=0)),
                ('total_calories', models.PositiveIntegerField(default=0)),
                ('track_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
