# Generated by Django 4.2.29 on 2026-04-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_moderation_hide_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytrack',
            options={'ordering': ['-created_at'], 'verbose_name': '활동 기록', 'verbose_name_plural': '활동 기록'},
        ),
        migrations.AlterModelOptions(
            name='dailyactivitysummary',
            options={'ordering': ['-date'], 'verbose_name': '일별 활동 요약', 'verbose_name_plural': '일별 활동 요약'},
        ),
    ]
