# Generated by Django 4.2.29 on 2026-04-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_moderation_hide_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': '댓글 좋아요', 'verbose_name_plural': '댓글 좋아요'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': '이야기 알림', 'verbose_name_plural': '이야기 알림'},
        ),
        migrations.AlterModelOptions(
            name='storycomment',
            options={'ordering': ['created_at'], 'verbose_name': '이야기 댓글', 'verbose_name_plural': '이야기 댓글'},
        ),
        migrations.AlterModelOptions(
            name='storylike',
            options={'verbose_name': '이야기 좋아요', 'verbose_name_plural': '이야기 좋아요'},
        ),
        migrations.AlterModelOptions(
            name='storyphoto',
            options={'ordering': ['order'], 'verbose_name': '이야기 사진', 'verbose_name_plural': '이야기 사진'},
        ),
        migrations.AlterModelOptions(
            name='walkstory',
            options={'ordering': ['-created_at'], 'verbose_name': '걸은 이야기', 'verbose_name_plural': '걸은 이야기'},
        ),
    ]
