# Generated by Django 4.2.29 on 2026-04-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_moderation_hide_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': '리뷰', 'verbose_name_plural': '리뷰'},
        ),
        migrations.AlterModelOptions(
            name='reviewhelpful',
            options={'verbose_name': '리뷰 도움됨', 'verbose_name_plural': '리뷰 도움됨'},
        ),
        migrations.AlterModelOptions(
            name='reviewimage',
            options={'ordering': ['order'], 'verbose_name': '리뷰 이미지', 'verbose_name_plural': '리뷰 이미지'},
        ),
    ]
