# Generated by Django 4.2.29 on 2026-04-04 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('name_ja', models.CharField(blank=True, max_length=100)),
                ('spot_type', models.CharField(choices=[('start', '출발'), ('restaurant', '맛집'), ('cafe', '카페'), ('photo', '포토스팟'), ('rest', '휴식'), ('view', '전망'), ('danger', '위험구간'), ('end', '도착')], max_length=20)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('order', models.PositiveIntegerField()),
                ('distance_from_start_km', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('description_en', models.TextField(blank=True, max_length=500)),
                ('description_ja', models.TextField(blank=True, max_length=500)),
                ('menu_highlight', models.CharField(blank=True, max_length=100)),
                ('price_range', models.CharField(blank=True, max_length=50)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('tip', models.TextField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', '승인대기'), ('approved', '승인됨'), ('rejected', '반려됨')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to=settings.AUTH_USER_MODEL)),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='trails.trail')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SpotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='spots/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spots.spot')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
