# Generated by Django 4.2.29 on 2026-04-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ['day_number', 'order']},
        ),
        migrations.AddField(
            model_name='spot',
            name='closed_days',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='spot',
            name='day_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='spot',
            name='is_must_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spot',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='spot',
            name='spot_type',
            field=models.CharField(choices=[('start', '출발'), ('restaurant', '맛집'), ('cafe', '카페'), ('photo', '포토스팟'), ('rest', '휴식'), ('view', '전망'), ('danger', '주의구간'), ('market', '시장/마켓'), ('gallery', '갤러리/문화공간'), ('temple', '절/사찰'), ('accommodation', '숙소'), ('transport', '교통편'), ('tip', '꿀팁 포인트'), ('end', '도착')], max_length=20),
        ),
    ]
