# Generated by Django 4.2.29 on 2026-04-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_moderation_hide_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ['day_number', 'order'], 'verbose_name': '스팟', 'verbose_name_plural': '스팟'},
        ),
        migrations.AlterModelOptions(
            name='spotimage',
            options={'ordering': ['order'], 'verbose_name': '스팟 이미지', 'verbose_name_plural': '스팟 이미지'},
        ),
    ]
