# Generated by Django 4.2.29 on 2026-04-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_alter_spot_options_alter_spotimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='spot_type',
            field=models.CharField(
                choices=[
                    ('start', '출발'),
                    ('restaurant', '맛집'),
                    ('cafe', '카페'),
                    ('photo', '포토스팟'),
                    ('rest', '휴식'),
                    ('view', '전망'),
                    ('danger', '주의구간'),
                    ('market', '시장/마켓'),
                    ('gallery', '갤러리/문화공간'),
                    ('temple', '절/사찰'),
                    ('accommodation', '숙소'),
                    ('transport', '교통편'),
                    ('tip', '꿀팁 포인트'),
                    ('toilet', '화장실'),
                    ('water', '식수대'),
                    ('store', '편의점/매점'),
                    ('pharmacy', '약국'),
                    ('hospital', '병원/의원'),
                    ('police', '경찰서/파출소'),
                    ('parking', '주차장'),
                    ('end', '도착'),
                ],
                max_length=20,
            ),
        ),
    ]
